# Generated by Django 3.1.4 on 2020-12-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.TextField()),
                ('ans', models.CharField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')], default=1, max_length=2)),
                ('difficulty', models.CharField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('pwd', models.CharField(default='', max_length=100)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
