# Generated by Django 3.1.4 on 2020-12-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gameId',
            field=models.CharField(choices=[('1', 'brickbreaker'), ('2', 'flappy'), ('3', 'pianotiles'), ('4', 'snake'), ('5', 'typing')], default=1, max_length=1),
        ),
    ]
