# Generated by Django 3.1.4 on 2020-12-26 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameId',
            field=models.CharField(choices=[('1', 'brickbreaker'), ('2', 'flappy'), ('3', 'pianotiles'), ('4', 'twotho'), ('5', 'typing')], default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='question',
            name='op1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='op2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='op3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='op4',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='App.user'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ans',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('1', 'Easy'), ('2', 'Medium'), ('3', 'Hard')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='pwd',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeNumber', models.CharField(choices=[('1', 'MbandP'), ('2', 'Nan'), ('3', 'FnH'), ('4', 'HCC'), ('5', 'SJA'), ('6', 'LHCC')], default=1, max_length=1)),
                ('score', models.IntegerField(default=0)),
                ('visited', models.BooleanField(default=False)),
                ('name', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='App.user')),
            ],
        ),
    ]
