# Generated by Django 3.1.4 on 2020-12-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20201218_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='op1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='op2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='op3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='op4',
            field=models.TextField(default=''),
        ),
    ]
