# Generated by Django 3.0.7 on 2020-12-27 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20201219_1832'),
        ('App', '0002_auto_20201227_0103'),
    ]

    operations = [
    ]
